platform :ios, '9.0'
use_frameworks!

pod 'Alamofire'
pod 'SwiftyJSON'
pod 'Fabric'
pod 'RealmSwift', '0.98.4'
pod 'Crashlytics'
pod 'UICountingLabel'
pod 'MCSwipeTableViewCell'
pod 'CVCalendar'
pod 'HanekeSwift'
pod 'XLPagerTabStrip'
pod 'PhoneNumberKit'
pod 'SwiftDate'
pod 'Eureka'
pod 'PureLayout'
