fastlane_version "1.97.2"
default_platform :ios

platform :ios do
  before_all do
    ensure_git_status_clean
    cocoapods
  end

  desc "Runs all the tests"
  lane :test do
    scan(scheme: "Athlete")
  end

  desc "Crashlytics beta"
  lane :beta do
    increment_build_number
    sigh(development: true, output_path: "/tmp")
    gym(
      scheme: "Athlete",
      use_legacy_build_api: true
    )
    crashlytics(
      api_token: ENV["CRASHLYTICS_API_TOKEN"],
      build_secret: ENV["CRASHLYTICS_BUILD_SECRET"],
      notes: "add some stuff",
      groups: ['dev-team-athlete']
    )
    create_commit_with_build_number
  end

  def create_commit_with_build_number
    build_number = Actions.lane_context[Actions::SharedValues::BUILD_NUMBER]
    sh "git add -A"
    sh "git commit -m \"Bulid \##{build_number}\""
  end

  after_all do |lane|
  end
end
