fastlane_version "1.59.0"

default_platform :ios

platform :ios do
  before_all do
    #cocoapods
    increment_build_number
    # xctool
  end

  desc "Runs all the tests"
  lane :test do
    # snapshot
  end

  desc "Crashlytics beta"
  lane :beta do
    gym(scheme: "Athlete")
    crashlytics(crashlytics_path: "./Pods/Crashlytics",
                emails: 'twistedplane@gmail.com')
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :testflight do
    sigh
    gym(scheme: "Athlete") # Build your app - more options available
    pilot
  end

  desc "Deploy a new version to the App Store"
  lane :deploy do
    # snapshot
    sigh
    gym(scheme: "Athlete") # Build your app - more options available
    # deliver(force: true)
    # frameit
  end

  after_all do |lane|
    build_number = Actions.lane_context[Actions::SharedValues::BUILD_NUMBER]
    sh "git add -A"
    sh "git commit -m \"Bulid \##{build_number}\""
  end
end
